/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gecedeneme;

/**
 *
 * @author Ayşe S. ERKMEN
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BillingBtn = new javax.swing.JButton();
        PetsBtn = new javax.swing.JButton();
        ProductManBtn = new javax.swing.JButton();
        CustomerManBtn = new javax.swing.JButton();
        CategoryManBtn = new javax.swing.JButton();
        LogOutBtn = new javax.swing.JButton();
        UsersBtn = new javax.swing.JButton();
        ButtonCustomersExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 228, 250));

        jPanel2.setBackground(new java.awt.Color(255, 246, 253));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setText("PupPet Shop");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 21)); // NOI18N
        jLabel2.setText("Admin Menu");

        BillingBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        BillingBtn.setForeground(new java.awt.Color(255, 102, 153));
        BillingBtn.setText("Billing");
        BillingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillingBtnActionPerformed(evt);
            }
        });

        PetsBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        PetsBtn.setForeground(new java.awt.Color(255, 102, 153));
        PetsBtn.setText("Pets");
        PetsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetsBtnActionPerformed(evt);
            }
        });

        ProductManBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        ProductManBtn.setForeground(new java.awt.Color(255, 102, 153));
        ProductManBtn.setText("Product Manger");
        ProductManBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductManBtnActionPerformed(evt);
            }
        });

        CustomerManBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        CustomerManBtn.setForeground(new java.awt.Color(255, 102, 153));
        CustomerManBtn.setText("Customer Manager");
        CustomerManBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerManBtnActionPerformed(evt);
            }
        });

        CategoryManBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        CategoryManBtn.setForeground(new java.awt.Color(255, 102, 153));
        CategoryManBtn.setText("Category Manager");
        CategoryManBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryManBtnActionPerformed(evt);
            }
        });

        LogOutBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        LogOutBtn.setForeground(new java.awt.Color(255, 102, 153));
        LogOutBtn.setText("Log Out");
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });

        UsersBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        UsersBtn.setForeground(new java.awt.Color(255, 102, 153));
        UsersBtn.setText("Users");
        UsersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CategoryManBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CustomerManBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ProductManBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PetsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BillingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(LogOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UsersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(BillingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PetsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(ProductManBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(CustomerManBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(CategoryManBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(LogOutBtn)
                .addGap(17, 17, 17))
        );

        ButtonCustomersExit.setBackground(new java.awt.Color(255, 255, 222));
        ButtonCustomersExit.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        ButtonCustomersExit.setForeground(new java.awt.Color(255, 111, 111));
        ButtonCustomersExit.setText("X");
        ButtonCustomersExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCustomersExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonCustomersExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonCustomersExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BillingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillingBtnActionPerformed
        new Billing().setVisible(true);
    }//GEN-LAST:event_BillingBtnActionPerformed

    private void PetsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetsBtnActionPerformed
        new Pets().setVisible(true);
    }//GEN-LAST:event_PetsBtnActionPerformed

    private void ProductManBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductManBtnActionPerformed
        new ProductManager().setVisible(true);
    }//GEN-LAST:event_ProductManBtnActionPerformed

    private void CustomerManBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerManBtnActionPerformed
        new CustomersManager().setVisible(true);
    }//GEN-LAST:event_CustomerManBtnActionPerformed

    private void CategoryManBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryManBtnActionPerformed
        new CategoryManager().setVisible(true);
    }//GEN-LAST:event_CategoryManBtnActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void ButtonCustomersExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCustomersExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ButtonCustomersExitActionPerformed

    private void UsersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersBtnActionPerformed
        new Users().setVisible(true);
    }//GEN-LAST:event_UsersBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {


        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BillingBtn;
    private javax.swing.JButton ButtonCustomersExit;
    private javax.swing.JButton CategoryManBtn;
    private javax.swing.JButton CustomerManBtn;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JButton PetsBtn;
    private javax.swing.JButton ProductManBtn;
    private javax.swing.JButton UsersBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
