/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gecedeneme;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muharrem
 */
public class CustomersManager extends javax.swing.JFrame {

    
    PraperedStatement prpStatement = null;
    
    Statement statement = null;
    Connection connection = null;
    ResultSet resultSet = null;
    
    public CustomersManager() {
        initComponents();
        ShowCustomer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CustomersName = new javax.swing.JTextField();
        CustomersAddress = new javax.swing.JTextField();
        CustomersPhone = new javax.swing.JTextField();
        ButtonCustomersEdit = new javax.swing.JButton();
        ButtonCustomersSave = new javax.swing.JButton();
        ButtonCustomersDelete = new javax.swing.JButton();
        ButtonCustomersExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CustomersTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(255, 228, 250));

        jPanel5.setBackground(new java.awt.Color(255, 255, 241));

        jPanel6.setBackground(new java.awt.Color(255, 246, 253));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel6.setText("PupPet Customers Manager");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setText("Name:");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel9.setText("Address:");

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel10.setText("Phone:");

        CustomersName.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        CustomersName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomersNameActionPerformed(evt);
            }
        });

        CustomersAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomersAddressActionPerformed(evt);
            }
        });

        CustomersPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomersPhoneActionPerformed(evt);
            }
        });

        ButtonCustomersEdit.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        ButtonCustomersEdit.setForeground(new java.awt.Color(255, 102, 153));
        ButtonCustomersEdit.setText("Edit");
        ButtonCustomersEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCustomersEditActionPerformed(evt);
            }
        });

        ButtonCustomersSave.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        ButtonCustomersSave.setForeground(new java.awt.Color(255, 102, 153));
        ButtonCustomersSave.setText("Save");
        ButtonCustomersSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCustomersSaveActionPerformed(evt);
            }
        });

        ButtonCustomersDelete.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        ButtonCustomersDelete.setForeground(new java.awt.Color(255, 102, 153));
        ButtonCustomersDelete.setText("Delete");
        ButtonCustomersDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCustomersDeleteActionPerformed(evt);
            }
        });

        ButtonCustomersExit.setBackground(new java.awt.Color(255, 255, 222));
        ButtonCustomersExit.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        ButtonCustomersExit.setForeground(new java.awt.Color(255, 111, 111));
        ButtonCustomersExit.setText("X");
        ButtonCustomersExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCustomersExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(278, 278, 278)
                        .addComponent(ButtonCustomersExit))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(CustomersName, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ButtonCustomersEdit)
                                .addGap(55, 55, 55)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(ButtonCustomersSave)
                                .addGap(94, 94, 94)
                                .addComponent(ButtonCustomersDelete)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(CustomersAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(CustomersPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ButtonCustomersExit))
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomersName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomersAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomersPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCustomersEdit)
                    .addComponent(ButtonCustomersSave)
                    .addComponent(ButtonCustomersDelete))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );

        CustomersTable.setBackground(new java.awt.Color(255, 255, 234));
        CustomersTable.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        CustomersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CustId", "Name", "Address", "Phone"
            }
        ));
        CustomersTable.setRowHeight(35);
        CustomersTable.setSelectionBackground(new java.awt.Color(255, 204, 204));
        CustomersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomersTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CustomersTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteAll(){
        CustomersName.setText("");
        CustomersAddress.setText("");
        CustomersPhone.setText("");
    }
    
    int itemId;
    Statement statement1 = null;
    ResultSet resultSet1 = null;
    public void Counter(){
        try 
        {
            statement1 = (Statement) connection.createStatement();
            resultSet1 = statement1.executeQuery("select Max(CustId) from CustomersTable");
            resultSet1.next();
            itemId = resultSet1.getInt(1)+1;
        }
        catch (Exception e) 
        {
            
        }
    }
    
    private void ShowCustomer(){
        try
        {
            connection = (Connection)DriverManager.getConnection(""); //bu kisma mysql'den data gelecek locakhost. tinak icine
            Statement statement = (Statement) connection.createStatement();
            resultSet = statement.executeQuery("Select * from CustomersTable");
            CustomersTable.setModel(DbUtils.resultSetToTableModel(resultSet));
        } 
        catch (Exception e) 
        {
        
        }
    }
    
    private void CustomersNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomersNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomersNameActionPerformed

    private void CustomersAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomersAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomersAddressActionPerformed

    private void CustomersPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomersPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomersPhoneActionPerformed

    private void ButtonCustomersExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCustomersExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ButtonCustomersExitActionPerformed

    private void ButtonCustomersSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCustomersSaveActionPerformed
        
        
        if(CustomersName.getText().isEmpty() || CustomersPhone.getText().isEmpty() || CustomersAddress.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "!!! missing information warning, fill in all the information !!!");
        }else{
            try {
                Counter();
                connection = DriverManager.getConnection(""); //bu kisma mysql'den data gelecek locakhost. tinak icine
                PreparedStatement save = (PreparedStatement) connection.prepareStatement("insert into CustomersTable values(?,?,?,?)");
                save.setInt(1,itemId);
                save.setString(2,CustomersName.getText());
                save.setString(3,CustomersAddress.getText());
                save.setString(4,CustomersPhone.getText());
                
                
                int satir = save.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Customer added Successfully!");
                
                connection.close();
                ShowCustomer();
                DeleteAll();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
        
    }//GEN-LAST:event_ButtonCustomersSaveActionPerformed
    
    int key = 0;
    private void CustomersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomersTableMouseClicked
        
        DefaultTableModel model = (DefaultTableModel) CustomersTable.getModel();
        int busira = CustomersTable.getSelectedRow();
        key = Integer.valueOf(model.getValueAt(busira, 0).toString());
        CustomersName.setText(model.getValueAt(busira, 1).toString());
        CustomersAddress.setText(model.getValueAt(busira, 2).toString());
        CustomersPhone.setText(model.getValueAt(busira, 3).toString());
        
        
    }//GEN-LAST:event_CustomersTableMouseClicked

    private void ButtonCustomersEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCustomersEditActionPerformed
        
        if(CustomersName.getText().isEmpty() || CustomersPhone.getText().isEmpty() || CustomersAddress.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "!!! missing information warning, fill in all the information !!!");
        }else{
            try {
                connection = DriverManager.getConnection(""); //bu kisma mysql'den data gelecek locakhost. tinak icine
                PreparedStatement save = (PreparedStatement) connection.prepareStatement("update CustomersTable set CustName=?,CustAdd=?,CustPhone=? where CustId=?");
                save.setInt(4,key);
                save.setString(1,CustomersName.getText());
                save.setString(2,CustomersAddress.getText());
                save.setString(3,CustomersPhone.getText());
                
                
                int satir = save.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Customer edited Successfully!");
                
                connection.close();
                ShowCustomer();
                DeleteAll();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
        
        
    }//GEN-LAST:event_ButtonCustomersEditActionPerformed

    private void ButtonCustomersDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCustomersDeleteActionPerformed
        
        if(key == 0){
            JOptionPane.showMessageDialog(this, "!!! warning, select a customer !!!");
        }else{
            try {
                connection = DriverManager.getConnection(""); //bu kisma mysql'den data gelecek locakhost. tinak icine
                PreparedStatement save = (PreparedStatement) connection.prepareStatement("Delete from CustomersTable where CustId=?");
                save.setInt(1,key);
                
                
                
                int satir = save.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Customer deleted Successfully!");
                
                connection.close();
                ShowCustomer();
                DeleteAll();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
        
    }//GEN-LAST:event_ButtonCustomersDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomersManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomersManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomersManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomersManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomersManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCustomersDelete;
    private javax.swing.JButton ButtonCustomersEdit;
    private javax.swing.JButton ButtonCustomersExit;
    private javax.swing.JButton ButtonCustomersSave;
    private javax.swing.JTextField CustomersAddress;
    private javax.swing.JTextField CustomersName;
    private javax.swing.JTextField CustomersPhone;
    private javax.swing.JTable CustomersTable;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
