/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gecedeneme;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muharrem
 */
public class Pets extends javax.swing.JFrame {

    /**
     * Creates new form Pets
     */
    public Pets() {
        initComponents();
        GetCategories();
        ShowPets();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PetNameT = new javax.swing.JTextField();
        AmountT = new javax.swing.JTextField();
        PriceT = new javax.swing.JTextField();
        CatC = new javax.swing.JComboBox<>();
        EditBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PetsT = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 228, 250));

        jPanel2.setBackground(new java.awt.Color(255, 255, 241));

        jPanel3.setBackground(new java.awt.Color(255, 246, 253));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel1.setText("PupPet Pet Manager");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("Category:");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setText("Amount:");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setText("Price:");

        PetNameT.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        PetNameT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetNameTActionPerformed(evt);
            }
        });

        AmountT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountTActionPerformed(evt);
            }
        });

        PriceT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceTActionPerformed(evt);
            }
        });

        CatC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        EditBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        EditBtn.setForeground(new java.awt.Color(255, 102, 153));
        EditBtn.setText("Edit");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });

        SaveBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        SaveBtn.setForeground(new java.awt.Color(255, 102, 153));
        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(255, 102, 153));
        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 222));
        jButton7.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 111, 111));
        jButton7.setText("X");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(358, 358, 358)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(PetNameT, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(CatC, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(EditBtn)
                                        .addGap(77, 77, 77)
                                        .addComponent(SaveBtn)))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(AmountT, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(DeleteBtn)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(PriceT, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton7))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CatC)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PetNameT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AmountT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PriceT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditBtn)
                    .addComponent(SaveBtn)
                    .addComponent(DeleteBtn))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );

        PetsT.setBackground(new java.awt.Color(255, 255, 234));
        PetsT.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        PetsT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Category", "Amount", "Price"
            }
        ));
        PetsT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PetsTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PetsT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 PraperedStatement prpStatement = null;
    
    Statement statement = null;
    Connection connection = null;
    ResultSet resultSet = null;
    
       private void ShowPets(){
        try
        {
            connection = (Connection)DriverManager.getConnection(""); //bu kisma mysql'den data gelecek locakhost. tinak icine
            Statement statement = (Statement) connection.createStatement();
            resultSet = statement.executeQuery("Select * from PetsT");
            PetsT.setModel(DbUtils.resultSetToTableModel(resultSet));
        } 
        catch (Exception e) 
        {
        
        }
    }
       private void GetCategories(){
           try{
                connection = (Connection)DriverManager.getConnection(""); //bu kisma mysql'den data gelecek locakhost. tinak icine
            Statement statement = (Statement) connection.createStatement();
            resultSet = statement.executeQuery("Select * from CategoryT");
            while(resultSet.next()){
                int CatId=resultSet.getInt("CatId");
                CatC.addItem(CatId);
            }
           }catch(Exception e){
               
           }
       }
    private void PetNameTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetNameTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PetNameTActionPerformed

    private void AmountTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmountTActionPerformed

    private void PriceTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceTActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    int itemId;
    Statement statement1 = null;
    ResultSet resultSet1 = null;
     public void Counter(){
        try 
        {
            statement1 = (Statement) connection.createStatement();
            resultSet1 = statement1.executeQuery("select Max(PId) from PetsT");
            resultSet1.next();
            itemId = resultSet1.getInt(1)+1;
        }
        catch (Exception e) 
        {
            
        }
    }
    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
         if(PetNameT.getText().isEmpty()  || CatC.getSelectedIndex()==-1 || AmountT.getText().isEmpty()||PriceT.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "!!! missing information warning, fill in all the information !!!");
        }else{
            try {
                Counter();
                connection = DriverManager.getConnection(""); //bu kisma mysql'den data gelecek locakhost. tinak icine
                PreparedStatement save = (PreparedStatement) connection.prepareStatement("insert into PetT values(?,?,?,?,?)");
                save.setInt(1,itemId);
                save.setString(2,PetNameT.getText());
                save.setString(3,Integer.valueOf(CatC.getSelectedItem().toString()));
                save.setString(4,Integer.valueOf(AmountT.getText()));
                save.setString(5,Integer.valueOf(PriceT.getText()));
                
                
                int satir = save.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Product added Successfully!");
                
                connection.close();
                ShowPets();
                DeleteAll();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_SaveBtnActionPerformed
int key=0;
    private void PetsTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PetsTMouseClicked
         
        DefaultTableModel model = (DefaultTableModel) PetsT.getModel();
        int busira = PetsT.getSelectedRow();
        key = Integer.valueOf(model.getValueAt(busira, 0).toString());
        PetNameT.setText(model.getValueAt(busira, 1).toString());
        CatC.setSelectedItem(model.getValueAt(busira, 2).toString());
        AmountT.setText(model.getValueAt(busira, 3).toString());
        PriceT.setText(model.getValueAt(busira, 4).toString());
        
    }//GEN-LAST:event_PetsTMouseClicked

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
          if(PetNameT.getText().isEmpty() || CatC.getSelectedIndex()==-1|| AmountT.getText().isEmpty()|| PriceT.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "!!! missing information warning, fill in all the information !!!");
        }else{
            try {
                connection = DriverManager.getConnection(""); //bu kisma mysql'den data gelecek locakhost. tinak icine
                PreparedStatement save = (PreparedStatement) connection.prepareStatement("update PetsT set PetsT=?,PName=?,PCat=?,PAmount=?,Pprice=? where PId=?");
                  save.setInt(1,itemId);
                save.setString(2,PetNameT.getText());
                save.setString(3,Integer.valueOf(CatC.getSelectedItem().toString()));
                save.setString(4,Integer.valueOf(AmountT.getText()));
                save.setString(5,Integer.valueOf(PriceT.getText()));
                
                
                
                int satir = save.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Pet edited Successfully!");
                
                connection.close();
                ShowPets();
                DeleteAll();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
        
    }//GEN-LAST:event_EditBtnActionPerformed
    private void DeleteAll(){
        PetNameT.setText("");
        AmountT.setText("");
        PriceT.setText("");
        CatC.setSelectedIndex(-1);
    }
    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
         if(key == 0){
            JOptionPane.showMessageDialog(this, "!!! warning, select a product !!!");
        }else{
            try {
                connection = DriverManager.getConnection(""); //bu kisma mysql'den data gelecek locakhost. tinak icine
                PreparedStatement save = (PreparedStatement) connection.prepareStatement("Delete from PetsT where PId=?");
                save.setInt(1,key);
                
                
                
                int satir = save.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Pet deleted Successfully!");
                
                connection.close();
                ShowPets();
               DeleteAll();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountT;
    private javax.swing.JComboBox<String> CatC;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JTextField PetNameT;
    private javax.swing.JTable PetsT;
    private javax.swing.JTextField PriceT;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
